# Usa una imagen base de Node.js
FROM node:18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de la app
COPY package*.json ./
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto (ajustar si usas otro)
EXPOSE 3000

# Iniciar la aplicación
CMD ["node", "src/server.js"]
